import 'package:flutter/material.dart';


const lightColorScheme = ColorScheme(
    brightness : Brightness.light,
    primary : Color(0xFF0060AB),
    onPrimary : Color(0xFFFFFFFF),
    primaryContainer : Color(0xFFD3E3FF),
    onPrimaryContainer : Color(0xFF001C39),
    secondary : Color(0xFF525F73),
    onSecondary : Color(0xFFFFFFFF),
    secondaryContainer : Color(0xFFD6E3FB),
    onSecondaryContainer : Color(0xFF0F1C2D),
    tertiary : Color(0xFF6E557A),
    onTertiary : Color(0xFFFFFFFF),
    tertiaryContainer : Color(0xFFF5D9FF),
    onTertiaryContainer : Color(0xFF271233),
    error : Color(0xFFBA1A1A),
    onError : Color(0xFFFFFFFF),
    errorContainer : Color(0xFFFFDAD6),
    onErrorContainer : Color(0xFF410002),
    background : Color(0xFFFDFCFF),
    onBackground : Color(0xFF1A1C1E),
    surface : Color(0xFFFDFCFF),
    onSurface : Color(0xFF1A1C1E),
    surfaceVariant : Color(0xFFDFE2EB),
    onSurfaceVariant : Color(0xFF43474E),
    outline : Color(0xFF73777F),
    shadow : Color(0xFF000000),
    inverseSurface : Color(0xFF2F3033),
    onInverseSurface : Color(0xFFF1F0F4),
    inversePrimary : Color(0xFFA3C9FF),
    surfaceTint : Color(0xFF0060AB),
);

const darkColorScheme = ColorScheme(
    brightness : Brightness.dark,
    primary : Color(0xFFA3C9FF),
    onPrimary : Color(0xFF00315C),
    primaryContainer : Color(0xFF004882),
    onPrimaryContainer : Color(0xFFD3E3FF),
    secondary : Color(0xFFBAC7DE),
    onSecondary : Color(0xFF243143),
    secondaryContainer : Color(0xFF3B485A),
    onSecondaryContainer : Color(0xFFD6E3FB),
    tertiary : Color(0xFFDBBCE7),
    onTertiary : Color(0xFF3E2849),
    tertiaryContainer : Color(0xFF553E61),
    onTertiaryContainer : Color(0xFFF5D9FF),
    error : Color(0xFFFFB4AB),
    onError : Color(0xFF690005),
    errorContainer : Color(0xFF93000A),
    onErrorContainer : Color(0xFFFFB4AB),
    background : Color(0xFF1A1C1E),
    onBackground : Color(0xFFE3E2E6),
    surface : Color(0xFF1A1C1E),
    onSurface : Color(0xFFE3E2E6),
    surfaceVariant : Color(0xFF43474E),
    onSurfaceVariant : Color(0xFFC3C6CF),
    outline : Color(0xFF8D9199),
    shadow : Color(0xFF000000),
    inverseSurface : Color(0xFFE3E2E6),
    onInverseSurface : Color(0xFF2F3033),
    inversePrimary : Color(0xFF0060AB),
    surfaceTint : Color(0xFFA3C9FF),
    
);
